### ISSUE TITLE
How to do native compilation for Windows Form?

### ISSUE THREAD

**Issue by Spoiledpay** [ypyf/Clound#1]
Dear,

how can I do a native build for applications that use Windows Forms? Since some .NET languages ​​use compilation directive - Winexe as compilation parameter. Can you help me with this?

A good piece of work has done so far in your language.

like this: compiler.exe /reference:d:\temp\tools\System.Windows.Forms.dll /target:winexe basic-window.txt

**Comment by ypyf** [comment]
This project has been inactive for a long time.
